In [4]:
def fizzbuzz(number):
    fizz = (number % 3) == 0
    buzz = (number % 5) == 0
    
    if fizz and buzz:
        return "fizzbuzz"
    elif fizz:
        return "fizz"
    elif buzz:
        return "buzz"
    else:
        return str(number)

In [6]:
fizzbuzz(3)

'fizz'

In [11]:
for n in range(1,16):
    print(fizzbuzz(n))

1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz

In [20]:
import random

numbers = random.sample(range(1, 1_000_000), 100_000)
numbers

[466893,
 379582,
 579363,
 241632,
 149996,
 165647,
 278436,
 688087,
 601581,
 374540,
 748517,
 478155,
 616689,
 113421,
 985123,
 842940,
 141653,
 161310,
 438714,
 608768,
 919219,
 138237,
 834499,
 752304,
 990767,
 359558,
 253867,
 63279,
 420203,
 680825,
 746934,
 848625,
 218932,
 826691,
 610823,
 697081,
 603812,
 744817,
 621120,
 546351,
 238836,
 854993,
 909171,
 436569,
 239097,
 284838,
 280642,
 838207,
 80307,
 995813,
 909190,
 750997,
 379630,
 990146,
 965479,
 918064,
 124847,
 772169,
 168354,
 18096,
 630674,
 812967,
 742756,
 905504,
 808842,
 589659,
 254228,
 55376,
 802854,
 487141,
 531866,
 364660,
 923287,
 287988,
 940463,
 396691,
 761647,
 37566,
 894492,
 108897,
 489480,
 662908,
 848926,
 313455,
 757462,
 393057,
 563715,
 479636,
 191371,
 344048,
 185608,
 792348,
 687233,
 425411,
 328587,
 875629,
 838122,
 432477,
 921177,
 85205,
 388995,
 787612,
 318239,
 960657,
 706433,
 558178,
 492256,
 139260,
 623686,
 771595,
 808699,
 260013,
 236719,
 757141,
 714101,
 386632,
 645000,
 897780,
 226401,
 252250,
 492645,
 655408,
 884208,
 57375,
 814295,
 589707,
 890236,
 378012,
 123237,
 888278,
 395602,
 672502,
 215355,
 843929,
 119193,
 341022,
 705663,
 133722,
 646540,
 532737,
 13180,
 61866,
 498671,
 62477,
 801762,
 962678,
 708301,
 363512,
 516620,
 959058,
 982271,
 920485,
 908678,
 822773,
 407424,
 508833,
 365213,
 225818,
 311708,
 794701,
 865557,
 998795,
 284829,
 108498,
 690508,
 961772,
 561832,
 247688,
 267179,
 934065,
 810077,
 112821,
 826265,
 429418,
 617371,
 251550,
 414845,
 367599,
 75101,
 420231,
 68282,
 604194,
 882801,
 747031,
 506232,
 300293,
 667650,
 755554,
 493237,
 68435,
 372142,
 733739,
 959421,
 59883,
 803555,
 740876,
 237652,
 60005,
 437322,
 473801,
 978046,
 425522,
 60536,
 634788,
 24056,
 31089,
 631641,
 361672,
 800621,
 747520,
 594782,
 35371,
 531697,
 775893,
 607246,
 172466,
 417133,
 698610,
 530031,
 866026,
 109802,
 774989,
 784475,
 434843,
 418148,
 468363,
 409812,
 957466,
 264200,
 335150,
 418716,
 830029,
 386977,
 725390,
 665527,
 233593,
 724726,
 454637,
 211471,
 538987,
 575323,
 723003,
 78942,
 992145,
 314977,
 553003,
 280910,
 277011,
 614963,
 551165,
 769362,
 767420,
 5726,
 612454,
 34997,
 695376,
 742742,
 452434,
 520719,
 390654,
 233023,
 60809,
 312571,
 765686,
 682117,
 305988,
 871246,
 233925,
 588735,
 914072,
 472343,
 440536,
 28207,
 304884,
 363744,
 430145,
 734096,
 736929,
 363797,
 543546,
 571596,
 238471,
 598866,
 740825,
 127410,
 658413,
 703130,
 516703,
 384507,
 422444,
 3984,
 955102,
 190683,
 625417,
 852866,
 432483,
 500219,
 187237,
 423819,
 586242,
 395396,
 695992,
 790782,
 539946,
 148533,
 399158,
 879138,
 909430,
 880693,
 737509,
 926391,
 865525,
 212590,
 109045,
 470433,
 894616,
 704774,
 616400,
 798186,
 555356,
 614142,
 564949,
 159780,
 847586,
 515820,
 443879,
 266058,
 873616,
 850430,
 872614,
 342129,
 163774,
 115389,
 402612,
 872597,
 904638,
 142613,
 575179,
 55194,
 457767,
 175591,
 585781,
 656344,
 487256,
 312685,
 193,
 925935,
 344547,
 168486,
 331889,
 181147,
 457052,
 460027,
 92749,
 343429,
 313089,
 622594,
 222341,
 542386,
 718602,
 374480,
 83409,
 122773,
 743739,
 358808,
 430740,
 659192,
 332013,
 522028,
 186065,
 210522,
 270343,
 247094,
 110364,
 147392,
 455088,
 267937,
 80600,
 3634,
 3642,
 870646,
 615754,
 42546,
 771608,
 724210,
 410638,
 416168,
 65776,
 777239,
 337827,
 671628,
 553469,
 87736,
 241785,
 73087,
 592827,
 746551,
 431347,
 791960,
 101930,
 547630,
 798648,
 213890,
 441770,
 596406,
 902438,
 972144,
 14691,
 514826,
 415922,
 747676,
 176895,
 648004,
 79074,
 295667,
 177901,
 154602,
 342219,
 165194,
 486818,
 268279,
 602777,
 63156,
 100843,
 216823,
 551746,
 776229,
 918315,
 561144,
 264093,
 888060,
 400173,
 205366,
 130797,
 303632,
 354946,
 202395,
 822990,
 51113,
 77420,
 284890,
 431714,
 536437,
 222450,
 175626,
 801563,
 556163,
 930072,
 881675,
 50646,
 776899,
 859230,
 929919,
 605554,
 577586,
 609915,
 768969,
 978223,
 821391,
 484314,
 169268,
 908656,
 640057,
 690141,
 925243,
 609640,
 567112,
 654262,
 430674,
 802470,
 898552,
 997311,
 629019,
 237923,
 444114,
 252709,
 693552,
 56502,
 85338,
 76920,
 270007,
 120421,
 897103,
 95996,
 844237,
 698707,
 32677,
 565737,
 208231,
 93414,
 937244,
 526238,
 767492,
 966755,
 799027,
 110218,
 305239,
 271597,
 379600,
 785458,
 901244,
 689280,
 665118,
 473577,
 688339,
 366588,
 324559,
 272976,
 345183,
 957079,
 942208,
 442072,
 893095,
 351805,
 461158,
 298929,
 715540,
 850304,
 685659,
 793191,
 902555,
 967574,
 65459,
 83362,
 503040,
 541243,
 993172,
 339892,
 956044,
 925881,
 860649,
 478913,
 32132,
 597004,
 369011,
 910440,
 368233,
 233853,
 375035,
 912508,
 534667,
 572950,
 620170,
 444004,
 395530,
 813557,
 469929,
 979491,
 230636,
 71683,
 258950,
 678822,
 951438,
 947381,
 363437,
 657023,
 43978,
 829521,
 497752,
 976806,
 57863,
 880861,
 898534,
 113797,
 89883,
 871712,
 738556,
 857764,
 538954,
 753303,
 849922,
 426302,
 576380,
 407653,
 572554,
 997449,
 331516,
 29987,
 488656,
 104423,
 197005,
 807048,
 54753,
 237477,
 28091,
 529825,
 982912,
 327241,
 686010,
 816680,
 667643,
 796895,
 103388,
 732737,
 191190,
 38490,
 811290,
 594648,
 518563,
 94515,
 910411,
 672638,
 672646,
 669100,
 888576,
 245,
 32484,
 269237,
 280289,
 212935,
 933048,
 783106,
 270622,
 644587,
 152490,
 292140,
 246316,
 604379,
 41770,
 969773,
 314995,
 643561,
 795961,
 320459,
 751993,
 461226,
 33695,
 595170,
 705684,
 325802,
 946686,
 536633,
 883080,
 55076,
 869395,
 600003,
 596560,
 737580,
 225095,
 376229,
 132968,
 533679,
 309568,
 612100,
 457745,
 471837,
 768246,
 435212,
 497701,
 755474,
 253574,
 518983,
 628638,
 279809,
 33041,
 550196,
 492870,
 267278,
 856503,
 229116,
 994389,
 685594,
 839473,
 875340,
 395858,
 757441,
 172064,
 353501,
 472235,
 432704,
 493183,
 35904,
 522546,
 209436,
 101438,
 203984,
 555705,
 107020,
 463343,
 164896,
 90573,
 100444,
 104056,
 250399,
 435724,
 67455,
 856,
 991704,
 158955,
 776846,
 92534,
 970351,
 259033,
 696256,
 314818,
 643874,
 396368,
 578146,
 343350,
 216250,
 229907,
 865490,
 620834,
 122301,
 225153,
 776745,
 480720,
 869431,
 636589,
 697191,
 524154,
 391532,
 158198,
 215498,
 174965,
 390,
 779027,
 894364,
 747321,
 990936,
 218990,
 485431,
 414753,
 608489,
 755296,
 420748,
 764813,
 848244,
 618463,
 86843,
 839438,
 646887,
 691342,
 28347,
 427756,
 404212,
 208421,
 26036,
 774371,
 128049,
 34405,
 460785,
 110692,
 20567,
 565203,
 271086,
 809382,
 148624,
 455919,
 31155,
 692693,
 908730,
 864069,
 810421,
 717575,
 585740,
 709556,
 658654,
 512289,
 307243,
 700404,
 176588,
 962419,
 126126,
 287254,
 197654,
 82861,
 151235,
 457608,
 970207,
 220546,
 587403,
 876482,
 103816,
 508853,
 793957,
 976914,
 18906,
 309683,
 331619,
 320419,
 997324,
 65015,
 169369,
 939688,
 762378,
 116123,
 530324,
 107134,
 42050,
 545370,
 415290,
 510941,
 537996,
 223379,
 319248,
 714055,
 463497,
 214207,
 25150,
 224320,
 412496,
 807465,
 753655,
 517952,
 363494,
 742365,
 424154,
 406661,
 431381,
 385927,
 403799,
 137618,
 729693,
 408731,
 560774,
 733603,
 962072,
 650960,
 194170,
 449861,
 763067,
 370299,
 648940,
 346683,
 198376,
 167634,
 430910,
 188752,
 704714,
 53206,
 756138,
 210053,
 164848,
 525620,
 498414,
 403112,
 890126,
 51208,
 671260,
 43304,
 743620,
 738336,
 145893,
 838162,
 137358,
 669399,
 827457,
 227857,
 659772,
 789167,
 418558,
 311716,
 293147,
 855174,
 177202,
 137422,
 990619,
 124118,
 533289,
 660100,
 518717,
 418730,
 762697,
 663614,
 818270,
 502025,
 684454,
 281477,
 159729,
 733351,
 406131,
 409334,
 524734,
 241582,
 488117,
 176210,
 723351,
 169243,
 956326,
 159046,
 716485,
 786789,
 243032,
 279523,
 107401,
 837161,
 69500,
 13269,
 905882,
 993729,
 950198,
 691594,
 831606,
 894223,
 282196,
 794590,
 228055,
 288292,
 958520,
 67046,
 209295,
 874471,
 801224,
 143126,
 661365,
 164397,
 892580,
 964850,
 48822,
 607630,
 286043,
 144348,
 668358,
 418019,
 879674,
 864558,
 5173,
 498876,
 419180,
 933639,
 571243,
 951696,
 819299,
 666560,
 235306,
 277491,
 609623,
 29083,
 829488,
 538746,
 814059,
 221499,
 545904,
 732043,
 79076,
 665815,
 194362,
 701867,
 837428,
 619744,
 128572,
 638429,
 676841,
 719165,
 667270,
 71275,
 552026,
 394630,
 564427,
 149197,
 433694,
 243132,
 252160,
 376543,
 510208,
 584241,
 507763,
 345481,
 606870,
 986346,
 796803,
 382345,
 395413,
 903132,
 906348,
 472839,
 754349,
 231130,
 159801,
 985898,
 785500,
 909592,
 94408,
 949480,
 118210,
 164895,
 131710,
 15453,
 605848,
 276176,
 677087,
 515675,
 844164,
 910721,
 716851,
 894588,
 26977,
 463997,
 590259,
 930520,
 181092,
 751870,
 111272,
 254459,
 355991,
 120964,
 393919,
 593751,
 883548,
 ...]

In [31]:
import pandas as pd

examples = [(n, fizzbuzz(n)) for n in numbers]

In [32]:
examples = pd.DataFrame(examples, columns=['n', 'fizzbuzz'])
examples.head()

        n fizzbuzz
0  466893     fizz
1  379582   379582
2  579363     fizz
3  241632     fizz
4  149996   149996

In [37]:
examples['fizz'] = examples['fizzbuzz'].str.contains('fizz', na=False)
examples['buzz'] = examples['fizzbuzz'].str.contains('buzz', na=False)
examples.head(10)

        n fizzbuzz   fizz   buzz
0  466893     fizz   True  False
1  379582   379582  False  False
2  579363     fizz   True  False
3  241632     fizz   True  False
4  149996   149996  False  False
5  165647   165647  False  False
6  278436     fizz   True  False
7  688087   688087  False  False
8  601581     fizz   True  False
9  374540     buzz  False   True